services:
  api:
    build: .
    container_name: api-demo
    expose:
      - "8000"

  nginx:
    image: nginx:alpine
    container_name: api-nginx
    ports:
      - "80:80"
    depends_on:
      - api
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

